<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.Master" AutoEventWireup="true" CodeBehind="ModelTabelarni.aspx.cs" Inherits="KorisnickiInterfejs.RacunTabelarni" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <style type="text/css">
        .style1
        {
            width: 215px;
        }
        .style2
        {
            font-size: large;
            color: #0066FF;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <table style="width:100%;">
        <tr>
            <td class="style1">
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style1">
                &nbsp;</td>
            <td class="style2">
                <strong>TABELARNI PRIKAZ MODELA</strong></td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style1">
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style1">
                &nbsp;</td>
            <td>
                <asp:Label ID="Label1" runat="server" Text="NAZIV MODELA"></asp:Label>
                <asp:TextBox ID="txbFilter" runat="server"></asp:TextBox>
                <asp:Button ID="brnFiltriraj" runat="server" onclick="brnFiltriraj_Click" 
                    Text="FILTRIRAJ" />
                <asp:Button ID="btnSvi" runat="server" onclick="btnSvi_Click" Text="SVI" 
                    Width="92px" />
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style1">
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style1">
                &nbsp;</td>
            <td style="margin-left: 40px">
                <asp:GridView ID="gvModeli" runat="server" Height="205px" Width="398px" 
                    AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" 
                    onselectedindexchanged="gvModeli_SelectedIndexChanged"
                    OnRowDeleting="gvModeli_OnRowDeleted" AutoGenerateEditButton="True"
                    OnRowEditing="gvModeli_OnRowEdit" BorderStyle="Solid"
                    >
                    <SelectedRowStyle BackColor="#66CCFF" />
                </asp:GridView>
                <asp:Button ID="btnDelete" runat="server" onclick="btnDelete_Click" 
                    Text="DELETE" Visible="False" />
            </td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style1">
                &nbsp;</td>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
    </table>
</asp:Content>
